hosters_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("hosters/", include("main_page.urls")),
    path('accounts/', include('allauth.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_page/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static  
from main_page.views import hosters_main, login, match, survey_view, increment


app_name = 'hosters'


urlpatterns = [
    path('main/', hosters_main, name='main'),
    path('login/', login, name='login'),
    path('match/', match, name='match'),
    path('mypage/', survey_view, name='mypage'),
    
    path('increment/', increment, name='increment')
    # 다른 URL 패턴들을 필요에 따라 추가
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{%  include 'head.html' %}

<body>

    {%  include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}


    <hr>

    {%  include 'footer.html' %}




</body>
</html>

templates/footer.html
<div style="text-align:center; margin-top: 2rem">
    <div class="hosters_footer_button">
        <span>문의 사항</span> |
        <span>공지</span> |
        <span>서비스 소개</span>
    </div>
    <div>
        <h6 class="hosters_logo" >hosters</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8" />
    <title>호스터스 Hosters</title>

    <!-- boot strap link -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
        crossorigin="anonymous"
    />

    <!-- google font link -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=ADLaM+Display&family=Caveat:wght@700&display=swap"
        rel="stylesheet"
    />
    <link href="https://fonts.cdnfonts.com/css/goudy-stout" rel="stylesheet" />
    <link
        rel="stylesheet"
        as="style"
        crossorigin
        href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css"
    />

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        $.ajaxSetup({
            headers: { "X-CSRFToken": "{{csrf_token}}" },
        });
        var cards;
        // 현재 인덱스
        $(document).ready(function () {
            // 초기 페이지 로딩 시 카운트 값 불러오기
            // 다음 버튼 클릭 시
            $("#next-btn").click(function () {
                $.ajax({
                    url: "{% url 'hosters:increment' %}",
                    type: "POST",
                    success: function (ind, data) {
                        $("#count-display").text(data.score.score);
                    },
                });
            });
        });
    </script>
</head>

templates/header.html
<link rel="stylesheet" href="../static/css/header.css" />
<a class="name" href="/hosters/mypage/"
    >{{ user.last_name }}{{ user.first_name }}<span>님, 환영합니다</span></a
>
<div class="top">
    <div class="navi">
        <div class="bar">
            <a href="/hosters/main/">Main</a>
            <a href="/hosters/match/">Matched</a>
        </div>
        <div class="title">
            <a href="/hosters/main/"><span>Hosters</span></a>
        </div>
        <div class="bar">
            <a href="/hosters/mypage/">Myself</a>

            <form
                action="{% url 'account_logout' %}"
                method="post"
                style="
                    position: relative;
                    float: left;
                    width: 50%;
                    height: 100%;
                    margin: 0;
                "
            >
                {% csrf_token %}
                <button type="submit" id="out">Logout</button>
            </form>
        </div>
    </div>
</div>